### ISSUE TITLE
CI Testing

### ISSUE THREAD

**Issue by banesullivan** [sam-greenwood/taco_vis#8] opened 2019-09-30 20:41 UTC
Where exactly are the tests?

We should get a CI service on Travis/Azure to run the tests across all supported Python versions (#4 is relevant here)

per https://github.com/openjournals/joss-reviews/issues/1720

**Comment by malmans2** [comment] 2019-09-30 21:39
I agree on this one too, and I suggest to check the code coverage as well (e.g., [codecov](https://codecov.io/))

Also, when I run `test.py` I get the same animation that is in the directory `test_files`, but the png images are different. The structure of the images is similar, but values are zero everywhere.
![](https://user-images.githubusercontent.com/22245117/65918886-d8092680-e3a8-11e9-86ed-661518f7ca5f.png)

**Comment by sam-greenwood** [comment] 2019-10-13 17:17
With regards to a CI service (something I am aware of but have never used before), I wasn't sure how that would work for testing a graphical output, rather than say computation of a number. What would you recommend would be the best way to do that?

**Comment by banesullivan** [comment] 2019-10-13 18:06
Have a [sphinx-gallery](https://sphinx-gallery.github.io) where examples are run and automatically generate figures which upload to a documentation website is a great way to test/verify that all is well

**Comment by banesullivan** [comment] 2019-10-13 18:06
Trying to implement an image comparison scheme wouldn't be worth your effort for a project this small

**Comment by sam-greenwood** [comment] 2019-11-10 21:31
> I agree on this one too, and I suggest to check the code coverage as well (e.g., [codecov](https://codecov.io/))
> 
> Also, when I run `test.py` I get the same animation that is in the directory `test_files`, but the png images are different. The structure of the images is similar, but values are zero everywhere.
> ![](https://user-images.githubusercontent.com/22245117/65918886-d8092680-e3a8-11e9-86ed-661518f7ca5f.png)


I have set up Travis-CI to test that the code can produce the plots, that the example data used has values above and below zero, and that it can save the plots. I test python 3.5 and up, with all of them passing the test. Could you let me know what version you were using to produce this plot with all zeros as I was unable to reproduce this.

**Comment by malmans2** [comment] 2019-11-10 21:54
I still get the same problem for all figures produces by the test script (I tried from scratch).
This is what I did on my linux machine:
* Create a yml file with the packages to install:
```yml
name: taco_vis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - ffmpeg
```
* Install and activate the new environment:
```
conda env create -f environment_taco_vis.yml
conda activate taco_vis
```
* Clone and install taco_vis in the environment:
```
git clone https://github.com/sam-greenwood/taco_vis.git
cd taco_vis/
python setup.py install
```
* Run tests:
```
python tests.py 
```
I'm attaching a full list of packages installed: [pkgs_list.txt](https://github.com/sam-greenwood/taco_vis/files/3829081/pkgs_list.txt)

**Comment by sam-greenwood** [comment] 2019-11-10 22:44
Found the issue and fixed it (due to the nature of my example data. It was plotting the value of the data when theta=0, which in my example data set always gave 0). Thanks for finding that issue.

**Comment by banesullivan** [comment] 2020-02-03 04:11
@sam-greenwood, is this issue resolved now that you have an example gallery and tests passing on Travis?

**Comment by sam-greenwood** [comment] 2020-02-23 20:14
Hi @banesullivan, yes it's all fixed now. I'll close the issue.

**Closed as completed by sam-greenwood** 2020-02-23 20:14 UTC
